CREATE TABLE IF NOT EXISTS app_state (
  id TEXT PRIMARY KEY,
  data JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS clientes (
  documento TEXT PRIMARY KEY,
  nome TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ATIVO',
  telefone TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  cep TEXT NOT NULL DEFAULT '',
  bairro TEXT NOT NULL DEFAULT '',
  endereco TEXT NOT NULL DEFAULT '',
  numero TEXT NOT NULL DEFAULT '',
  complemento TEXT NOT NULL DEFAULT '',
  uf TEXT NOT NULL DEFAULT '',
  cidade TEXT NOT NULL DEFAULT '',
  observacoes TEXT NOT NULL DEFAULT '',
  razao_social TEXT NOT NULL DEFAULT '',
  nome_fantasia TEXT NOT NULL DEFAULT '',
  situacao_cnpj TEXT NOT NULL DEFAULT '',
  responsavel_nome TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS responsaveis (
  cpf TEXT PRIMARY KEY,
  cliente_documento TEXT NOT NULL REFERENCES clientes(documento) ON UPDATE CASCADE ON DELETE CASCADE,
  nome TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS responsaveis_cliente_documento_idx ON responsaveis(cliente_documento);

CREATE TABLE IF NOT EXISTS servicos (
  codigo TEXT PRIMARY KEY,
  nome TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ATIVO',
  frequencia TEXT NOT NULL DEFAULT '',
  tipo TEXT NOT NULL DEFAULT '',
  valor NUMERIC(14,2) NOT NULL DEFAULT 0,
  observacoes TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orcamentos (
  numero INTEGER PRIMARY KEY,
  cliente_documento TEXT NOT NULL REFERENCES clientes(documento) ON UPDATE CASCADE ON DELETE RESTRICT,
  data DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'EM ANÁLISE',
  observacoes TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS orcamentos_cliente_documento_idx ON orcamentos(cliente_documento);

CREATE TABLE IF NOT EXISTS orcamento_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  orcamento_numero INTEGER NOT NULL REFERENCES orcamentos(numero) ON UPDATE CASCADE ON DELETE CASCADE,
  posicao INTEGER NOT NULL,
  servico_codigo TEXT NOT NULL REFERENCES servicos(codigo) ON UPDATE CASCADE ON DELETE RESTRICT,
  quantidade NUMERIC(14,3) NOT NULL DEFAULT 0,
  valor_unitario NUMERIC(14,2) NOT NULL DEFAULT 0,
  desconto NUMERIC(14,2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (orcamento_numero, posicao)
);

CREATE INDEX IF NOT EXISTS orcamento_itens_servico_codigo_idx ON orcamento_itens(servico_codigo);

CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario TEXT NOT NULL UNIQUE,
  nome TEXT NOT NULL,
  email TEXT NOT NULL DEFAULT '',
  perfil TEXT NOT NULL DEFAULT 'OPERADOR',
  permissoes JSONB,
  senha_hash TEXT NOT NULL,
  deve_trocar_senha BOOLEAN NOT NULL DEFAULT FALSE,
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  superadmin_locked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessoes (
  token_hash TEXT PRIMARY KEY,
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS sessoes_usuario_id_idx ON sessoes(usuario_id);
CREATE INDEX IF NOT EXISTS sessoes_expires_at_idx ON sessoes(expires_at);

CREATE TABLE IF NOT EXISTS auditoria_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
  usuario TEXT NOT NULL DEFAULT '',
  perfil TEXT NOT NULL DEFAULT '',
  acao TEXT NOT NULL,
  modulo TEXT NOT NULL DEFAULT '',
  entidade_tipo TEXT NOT NULL DEFAULT '',
  entidade_id TEXT NOT NULL DEFAULT '',
  detalhes JSONB NOT NULL DEFAULT '{}'::jsonb,
  ip TEXT NOT NULL DEFAULT '',
  user_agent TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS auditoria_logs_created_at_idx ON auditoria_logs(created_at);
CREATE INDEX IF NOT EXISTS auditoria_logs_usuario_id_idx ON auditoria_logs(usuario_id);
CREATE INDEX IF NOT EXISTS auditoria_logs_usuario_idx ON auditoria_logs(usuario);
CREATE INDEX IF NOT EXISTS auditoria_logs_modulo_idx ON auditoria_logs(modulo);
CREATE INDEX IF NOT EXISTS auditoria_logs_acao_idx ON auditoria_logs(acao);

CREATE TABLE IF NOT EXISTS arquivos (
  categoria TEXT NOT NULL,
  nome TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  conteudo BYTEA NOT NULL,
  tamanho BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (categoria, nome)
);

CREATE INDEX IF NOT EXISTS arquivos_categoria_idx ON arquivos(categoria);
